apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "ignition-sync-operator.fullname" . }}-manager-rolebinding
  labels:
    {{- include "ignition-sync-operator.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "ignition-sync-operator.fullname" . }}-manager-role
subjects:
  - kind: ServiceAccount
    name: {{ include "ignition-sync-operator.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
