{{- if .Values.metrics.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "ignition-sync-operator.fullname" . }}-metrics-reader
  labels:
    {{- include "ignition-sync-operator.labels" . | nindent 4 }}
rules:
  - nonResourceURLs:
      - "/metrics"
    verbs:
      - get
{{- end }}
