{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "ignition-sync-operator.fullname" . }}-allow-metrics-traffic
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ignition-sync-operator.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "ignition-sync-operator.selectorLabels" . | nindent 6 }}
  policyTypes:
    - Ingress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              metrics: enabled
      ports:
        - port: {{ .Values.metrics.service.port }}
          protocol: TCP
{{- end }}
