apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "ignition-sync-operator.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ignition-sync-operator.labels" . | nindent 4 }}
