apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: ignition-sync-pod-injection
  annotations:
    cert-manager.io/inject-ca-from: ignition-sync-operator-system/ignition-sync-webhook-cert
webhooks:
  - name: pod-inject.sync.ignition.io
    admissionReviewVersions: ["v1"]
    clientConfig:
      service:
        name: webhook-service
        namespace: system
        path: /mutate-v1-pod
    failurePolicy: Ignore
    matchPolicy: Equivalent
    reinvocationPolicy: IfNeeded
    namespaceSelector:
      matchExpressions:
        - key: ignition-sync.io/injection
          operator: In
          values: ["enabled"]
    rules:
      - apiGroups: [""]
        apiVersions: ["v1"]
        operations: ["CREATE"]
        resources: ["pods"]
        scope: Namespaced
    sideEffects: None
    timeoutSeconds: 10
