# This configuration is for teaching kustomize how to update name and namespace reference in
# temporary patches for cert-manager injection.
nameReference:
  - kind: Issuer
    group: cert-manager.io
    fieldSpecs:
      - path: spec/issuerRef/name
        kind: Certificate
        group: cert-manager.io
